name: tp3 tests fonctionnels
 
on:
  push:
    branches: 
      - tp3
    paths: 
      - 'malib.c'
      - 'malib.h'
      - 'outil3.h'
      - 'outil3.c'
      - 'tp3.c'
      - '.gitignore/workflows/test-f.yml'
      - 'ressources/entree01.txt'
      - 'ressources/sortie01.txt'
      - 'ressources/entree02.txt'
      - 'ressources/sortie02.txt'
      - 'ressources/entree03.txt'
      - 'ressources/sortie03.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup |
        run: make
       
      - name: Test 1
        run: cat ressources/entree01.txt | ./tp3 | diff ressources/sortie01.txt -
        
      - name: Test 2
        run: cat ressources/entree02.txt | ./tp3 | diff ressources/sortie02.txt -

      - name: Test 3
        run: cat ressources/entree03.txt | ./tp3 | diff ressources/sortie03.txt -
      
      - name: push
        uses: actions-x/commit@v1
        with:
          name: GitHub Actions Autocommitter
          branch: tp3
          file: fonctionnel.md
