name: tp3 tests fonctionnels
 
on:
  push:
    branches: 
      - tp3
    paths: 
      - 'malib.c'
      - 'malib.h'
      - 'outil3.h'
      - 'outil3.c'
      - 'tp3.c'
      - '.gitignore/workflows/test-c.yml'
      - 'ressources/entree01.txt'
      - 'ressources/sortie01.txt'
      - 'ressources/entree02.txt'
      - 'ressources/sortie02.txt'
      - 'ressources/entree03.txt'
      - 'ressources/sortie03.txt'
      - 'ressources/entree04.txt'
      - 'ressources/sortie04.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
       
      - name: Test 1
        run: cat ressources/entree01.txt | ./tp3 | diff ressources/sortie01.txt -
        
      - name: Test 2
        run: cat ressources/entree02.txt | ./tp3 | diff ressources/sortie02.txt -

      - name: Test 3
        run: cat ressources/entree03.txt | ./tp3 | diff ressources/sortie03.txt -

      - name: Test 4
        run: cat ressources/entree04.txt | ./tp3 | diff ressources/sortie04.txt -
